### ISSUE TITLE
Add % of total population-column

### ISSUE THREAD

**Issue by egils-consulting** [salgo60/CoronaVaccinationCheck#1]
Very nice overview! I would like to see how many vaccines have been given as a % of the total population also.

**Comment by salgo60** [comment]
Tänkte även på det med det är lite kasst med Länkade data dom har landet som [location som är en textsträng](https://github.com/owid/covid-19-data/tree/master/public/data/vaccinations/country_data)...... 

![image](https://user-images.githubusercontent.com/14206509/103131954-3b186480-46a3-11eb-9b8d-cbae188f34c1.png)


Kollar du på detta data [covid.ourworldindata.org/data/owid-covid-data.json](https://covid.ourworldindata.org/data/owid-covid-data.json) så har dom hängt på mer data per land som gör det enkelt att göra mer jämförelser...


![image](https://user-images.githubusercontent.com/14206509/103131889-e70d8000-46a2-11eb-9b92-afbf63e4422f.png)

**Comment by salgo60** [comment]
- version 0.301 creates % of tiotal population see [Corona_VaccinationperCountryPopulation.png](https://github.com/salgo60/CoronaVaccinationCheck/blob/main/Corona_VaccinationperCountryPopulation.png?raw=true)

**Comment by salgo60** [comment]
Not easy this with open loosely coupled communities.... Now I found news data with xx

* folder [public/data/vaccinations](https://github.com/owid/covid-19-data/tree/master/public/data/vaccinations)
** has file [COVID-19 - Vaccinations.csv](https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/COVID-19%20-%20Vaccinations.csv)  with column **total_vaccinations_per_hundred** 
** has folder [public/data/vaccinations/country_data](https://github.com/owid/covid-19-data/tree/master/public/data/vaccinations/country_data) that I scan from my [Nootebook](https://github.com/salgo60/CoronaVaccinationCheck/blob/main/Check%20Corona%20Vaccination.ipynb)
