### ISSUE TITLE
Chinese numbers are fishy

### ISSUE THREAD

**Issue by egils-consulting** [salgo60/CoronaVaccinationCheck#10]
I suggest excluding them for now until they are less linear.

**Comment by salgo60** [comment]
ce la vie....

**Comment by salgo60** [comment]
I feel China has another scale than Sweden ;-) now 4 500 000

![image](https://user-images.githubusercontent.com/14206509/103479204-68b08c80-4dcc-11eb-8976-1d1de59f3e64.png)

**Comment by salgo60** [comment]
Feels China progress in a stable way now pass 9 000 000 see [China.csv](https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/China.csv)

I close this
